### ISSUE TITLE
puppetTodo: is not highlighted

### ISSUE THREAD

**Issue by misaflo** [rodjek/vim-puppet#124]
Hi,

Keywords puppetTodo (TODO, NOTE, FIXME, ...) are not highlighted if they are follow by ":".

Example:

    # TODO : my text   => highlight
    # TODO: my text    => not highlight

**Comment by lelutin** [comment]
I can reproduce this.

we seem to have somewhat the same thing as what python's default syntax script contains, but for python the case where the keyword is followed by a : does highlight corretly.

there's probably something else influencing this, but I still havent found out what

**Comment by lelutin** [comment]
from what I see this is caused by the value of `iskeyword` set in `ftplugin/puppet.vim`

**Comment by lelutin** [comment]
hmm .. trying to understand why `iskeyword` was set at all, I end up on commit 94a867ac5092204af317c089e0aef753b76fa73f which does not explain the reasoning why the value was set.

I'm wondering if we should remove the line that sets this variable entirely, but I currently don't know the implications that it'll have on the rest of the plugin.

currently I would venture a guess that `:` is included in keywords so that class and defined type names of the form `module::something` get matched up by syntax and/or other functionality.

**Comment by lelutin** [comment]
one thing that gets changed by removing `:` from `iskeyword` is movements over words (e.g. the `w` command currently skips over a full resource name with all colon characters in the name)

**Comment by lelutin** [comment]
Since this relates to the presence of `:` in `iskeyword`, it's then closeley related to #108

**Comment by lelutin** [comment]
This was fixed some time ago in the context of the issue linked above
