### ISSUE TITLE
Comment on line before end block causes indentation error

### ISSUE THREAD

**Issue by kellermark** [rodjek/vim-puppet#20]
If you have a code block "{ ... }" and the last line before the ending curly brace is a comment, the indentation of the last curly brace will line up with the comment instead of the beginning curly brace.

Example:

```
class foo
{
  notify { "my notice":}
  #foo goes here
  }
  class bar
  {
    notify { "my bar":}
  }
```

**Comment by lelutin** [comment]
This case is still broken after merging #51

**Comment by lelutin** [comment]
ok, I figured out the remaining issue and it's unrelated. It also means that the approach I've described above to fix the current issue is working nicely.

I'll send a pull request in a few minutes that shold close all of the currently indentation bug reports and also fix the bug that I've found above.

FYI the unrelated bug is caused by the call to `searchpair()` mistakenly matching inside comments and strings
