### ISSUE TITLE
> moves cursor after }

### ISSUE THREAD

**Issue by cdenneen** [rodjek/vim-puppet#31]
if I write:

``` puppet
class { it writes class {}
```

then 

``` puppet
class {'test':
  foo =>when i hit > here}
```

``` puppet
class {'test':
  foo => }cursor jumps here
```

**Comment by tobyoxborrow** [comment]
This is also annoying with mothership operators. So if you try and type:
```
<<||>>
```
Because of the cursor jump the second bracket will be typed at the beginning, you will end up with:
```
><<||>
```

**Comment by belminf** [comment]
Has anyone figured out what's causing this?

**Comment by Zipfer** [comment]
Have the same problem, got a hell when created a hashes and spaceships operators

**Comment by irgeek** [comment]
I've tracked this issue down to the hash rocket alignement code [here](https://github.com/rodjek/vim-puppet/blob/cce0312adcaa15c462aba89057565520c1928685/after/ftplugin/puppet.vim#L5-L7): 

```puppet
if g:puppet_align_hashes
    inoremap <buffer> <silent> > ><Esc>:call puppet#align#AlignHashrockets()<CR>$a
endif
```

The `inoremap` command there is remapping what happens when you type a `>`. Breaking it down, it does this:

- `>` - emit a `>` character because the one we just typed was consumed by the remapping
- `<Esc>` - press escape to exit insert mode
- `:call puppet#align#AlignHashrockets()<CR>` - Call the function that re-aligns the hash rockets
- `$` - *jump to the end of the line*
- `a` - enter insert mode

It makes sense to write it this way when you're typing new code because your cursor is likely at the end of the line when you type `>`. When you're editing a line to add `->` before a resource, though, it can be quite annoying because the cursor seems to magically jump to the end of the line.

I'm still trying to find a way to fix it.
