### ISSUE TITLE
Pattern type breaking highlighting

### ISSUE THREAD

**Issue by alexharv074** [rodjek/vim-puppet#94]
I found the following code example breaks the vim syntax highlighter:

``` puppet
class foo (
  Pattern[/(\d+[\.$]){4}/] $ipaddr,
) {
  notice($ipaddr)
}

class { 'foo': ipaddr => '1.1.1.1.' } 
```

It appears in vim as:

<img width="287" alt="screen shot 2018-07-02 at 7 05 43 pm" src="https://user-images.githubusercontent.com/2305330/42155316-6afb86b6-7e2b-11e8-8b56-90d1881303e3.png">

**Comment by alexharv074** [comment]
I worked around it using:

``` puppet
class foo (
  Pattern[/(\d+[\.$]){4}/] $ipaddr, #/ # comment is to trick vim syntax highlighter.
) {
  notice($ipaddr)
}

class { 'foo': ipaddr => '1.1.1.1.' }
```

**Comment by lelutin** [comment]
I can confirm that this is happening on current master.

we probably need to add a new zone type for regular expressions

**Comment by lelutin** [comment]
reading the current syntax hilighting code, I somehow think that this might be the issue: the `puppetInstance` syntax match zone stops matching at the opening curly brace or bracket. e.g. : https://github.com/rodjek/vim-puppet/blob/master/syntax/puppet.vim#L36

so I don,t know how to fix this currently since possibly we can't have `puppetInstance` "contain" the syntax match `puppetRegex` since that would not make any sense. should we have a higher-level zone that actually contains `puppetInstance` and then whatever is valid for values inside brackets?

**Comment by lelutin** [comment]
@alexharv074 I've re-tested your case on the current master and I believe that the recent merger of the new syntax highlighting has fixed this issue!
